### ISSUE TITLE
User can search an anime by title

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project-Whats-that-Anime-#1]
![image](https://user-images.githubusercontent.com/90743100/209754417-173be35b-88f1-45a1-a543-681fb65fffea.png)
![image](https://user-images.githubusercontent.com/90743100/209754449-2d83c3fe-1303-4ae6-afa2-5d7900fc238d.png)

## 💰 Motivation

Users will be able to search specific anime by title

## 📐 Plan

Create a responsive search box that will load anime thumbnails related to the title the user typed in.

## ✅ Task List

- [ ] Add a nav bar with title of website
- [ ] add a text area for the user to type in the anime title
- [ ] create a button to press after the user types in anime title to load anime thumbnails
- [ ] when the button is pressed, a submit/click event will load in thumbnails
- [ ] create a callback function for the event that will create new elements for the thumbnails based on the title that was typed in the search box
