### ISSUE TITLE
User can click thumbnail 

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project-Whats-that-Anime-#2]
![image](https://user-images.githubusercontent.com/90743100/209755080-68dff35f-a94c-46c4-8fbf-36761c707655.png)
![image](https://user-images.githubusercontent.com/90743100/209755097-19aa95ee-89fa-403b-98ae-6fc559b2838a.png)

## 💰 Motivation

If a user decides to click a thumbnail. A page will load that includes details of the anime

## 📐 Plan

Allow users to click thumbnail to generate a page with anime details

## ✅ Task List

- [ ] Add a click event for when the user clicks an anime thumbnail
- [ ] In the click event callback function, make a http request to jikan.moe to pull in relevant anime details data
- [ ] In the click event callback function, create the html elements for the anime details page 
- [ ]  In the click event callback function, add api data to the appropriate elements
